---
title: "Práctica 11. Anotación"
lang: es
date: today
execute: 
  output: true
  error: true
engine: knitr
bibliography: ../../doc/references.bib
language:
   title-block-published: "Última actualización:"
   section-title-references: "Bibliografía"
format:
   html:
      embed-resources: true
editor: 
  markdown: 
    wrap: 72
---

## Datos

El primero paso es decargar de Uniprot las 6023 proteínas que sabemos que codifica el cromosoma 4 de Arabidopsis thalina. Procedo a descomrpimir el archivo con `gunzip` en bash.

`gunzip -k ../../data/uniprotkb_proteome_UP000006548_AND_prot_2026_04_28.fasta.gz`


## Resultados

::: {.callout-note icon="false"}
## Ejercicio 1

Sabiendo que una forma de hacerlo es la siguiente, incluye la orden en un bloque de Bash de tu documento de Quarto de tal manera que el archivo de entrada esté en tu carpeta data y el de salida en la misma carpeta de trabajo de la práctica actual, y además, que sólo se ejecute si el archivo de salida proteinas.fasta no existe.

```{bash} 
if [ ! -e proteinas.fasta ]; then
  awk '(/^>/){split($1, A, /\|/); print ">" A[2]}(/^[^>]/){print $0}' \
  ../../data/uniprotkb_proteome_UP000006548_AND_prot_2026_04_28.fasta \
  > proteinas.fasta
fi
```
:::

Descargo los resultados: `RepeatMaskerResults.zip`, `RepeatModelerResults.zip` y `galba.zip`.

::: {.callout-note icon="false"}
## Ejercicio 2

Explora los resultados de `RepeatModeler` y trata de contestar las preguntas siguientes.

¿Cuántas familias de elementos transponibles se han encontrado?

```{bash}
grep -c "^>" ../../results/2026-04-28/RepeatModelerResults/RM_380234.MonApr202303552026/consensi.fa
```

¿Cuánto duró la ejecución del programa?

En `rmod.log`al final del todo proporciona la información del tiempo que duró la ejecución del programa. Program Time: 01:02:16 (hh:mm:ss) Elapsed Time

¿Cuál dirías que es el archivo de salida más importante?

Diría que es `consensi.fa.classified` porque proporciona las secuencias consenso de diferentes familias y les porporciona una clase.
:::

::: {.callout-note icon="false"}
## Ejercicio 3

1.  Instala el programa `bedtools` siguiendo las instrucciones oportunas para tu sistema en la página oficial.
Lo he instalado desde el Homebrew de Mac.

2.  Utiliza el ensamblaje original como archivo FASTA de entrada y el archivo `GFF` que ha producido `RepetaMasker` como coordenadas de las regiones a enmascarar. Lee el manual de `bedtools maskfasta` en este enlace y genera el ensamblaje con máscara suave llamado `At4.soft.fa`.

```{bash}
if [ ! -e At4.soft.fa ]; then
  bedtools maskfasta \
    -fi ../../results/2026-04-21/asm1/At4.fa \
    -bed ../../results/2026-04-28/RM01/At4.fa.out.gff \
    -soft \
    -fo At4.soft.fa
fi
```
:::

::: {.callout-note icon="false"}
## Ejercicio 4

Incluye en tu documento de Quarto un bloque de código (pero no ejecutable, con la opción `eval: false`) como el anterior, donde los caminos TSERBA y a MINIPROTHINT se correspondan con tu propia carpeta `bin`, aunque no los tengas instalados.

```{bash eval:false}
export TSEBRA_PATH=/home/raulrodfer/bin/TSEBRA/
export MINIPROTHINT_PATH=/home/raulrodfer/bin/miniprothint/

galba.pl --species="Arabidopsis thaliana" \
         --genome=At4.soft.fa \
         --prot_seq=proteinas.fasta
```
:::

::: {.callout-note icon="false"}
## Ejercicio 5 
:::
Échales un vistazo a los archivos de salida de GALBA y trata de sacar algo en claro.

```{bash}
head -n 5 GALBA/galba.gtf # Una tabla con coordenadas de los genes, de que herramienta vienen, el tipo de estructura y demás parámetros interesantes.
```

```{bash}
head -n 5 GALBA/galba.codingseq # Otro archivo FASTA que contiene las secuencias de los genes pero en NUCLEOTIDOS
```

```{bash}
head -n 5 GALBA/galba.aa # Un archivo tipo FASTA que contiene las secuencias de aminoacidos (las proteinas) de los genes que se han predicho
```

El `GALBA.log`deja documentan paso a paso la ejecución del proceso detallando tiempos y
posibles errores. 
Después hay otros archivos  relevantes como: `augustus.hints.gtf`, que contiene la anotación final de genes integrando evidencias externas (exones, CDS, intrones); a`ugustus.ab_initio.gtf`, con predicciones puramente ab initio sin pistas; `hintsfile.gff`, donde se recogen las evidencias (alineamientos de proteínas o RNA-seq) que guían la anotación.

::: {.callout-note icon="false"}
## Ejercicio 6 
:::

Si quieres, puedes intentar instalar GALBA en tu ordenador, tomando nota de las dificultades con las que te encuentras.

El ejercicio 6 no lo he realizado. 